// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Consumo struct {
	ID        string   `json:"id"`
	Data      string   `json:"data"`
	Valor     float64  `json:"valor"`
	Tipo      int      `json:"tipo"`
	VeiculoID string   `json:"veiculoId"`
	Veiculo   *Veiculo `json:"veiculo,omitempty"`
}

type Mutation struct {
}

type NewConsumo struct {
	Data      string  `json:"data"`
	Valor     float64 `json:"valor"`
	Tipo      int     `json:"tipo"`
	VeiculoID int     `json:"veiculoId"`
}

type NewVeiculo struct {
	Marca         string `json:"marca"`
	Modelo        string `json:"modelo"`
	Placa         string `json:"placa"`
	AnoFabricacao int    `json:"anoFabricacao"`
	AnoModelo     int    `json:"anoModelo"`
}

type Query struct {
}

type Veiculo struct {
	ID            string     `json:"id"`
	Marca         string     `json:"marca"`
	Modelo        string     `json:"modelo"`
	Placa         string     `json:"placa"`
	AnoFabricacao int        `json:"anoFabricacao"`
	AnoModelo     int        `json:"anoModelo"`
	Consumos      []*Consumo `json:"consumos,omitempty"`
}
